FROM node:18-alpine as build-stage
# The work directory will be /app.
# This Docker "instruction" will create that directory and go inside of it,
# + all the next steps will "be" in that /app directory:
WORKDIR /usr/src/app

# copy all files that start with package and end with json into the /app directorie
COPY package*.json ./

# install the dependencies
RUN npm install

# copy the content of the pwd into the /app directorie
COPY ./ ./

# run the npm build command to compile the source code inside the docker container
RUN npm run build

# Stage 1, based on Nginx, to have only the compiled app, ready for production with Nginx
FROM nginx:alpine

# from the build-stage copy the the compiled app
COPY --from=build-stage /usr/src/app/build/ /usr/share/nginx/html

# remove the default config file
RUN rm /etc/nginx/conf.d/default.conf

# Copy the default nginx.conf provided by tiangolo/node-frontend

COPY nginx/nginx.conf /etc/nginx/conf.d

# expose port 80
EXPOSE 80

# fire up nginx
CMD ["nginx", "-g", "daemon off;"]