version: "3.7"
services:
  client:
    container_name: client-dev
    image: client-dev
    working_dir: /app
    build: 
      context: ./client
      dockerfile: Dockerfile-dev
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
      - /app/node_modules
    depends_on:
      - server
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      
  server:
    container_name: server-dev
    build:
      context: ./server
      dockerfile: Dockerfile-dev
    ports:
      - 5000:5000
    volumes:
      - ./server:/app
      - /app/node_modules
