version: "3.7"
services:
  portfolio-server:
    image: yannickkloud/portfolio:server-latest
    env_file:
      - .env
    container_name: portfolio-server
    restart: unless-stopped
    profiles: ["portfolio"]
    working_dir: /usr/src/app
    environment:
      NODE_ENV: production
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      PORT: 5000
    networks:
      - portfolio_network

  portfolio-client:
    image: yannickkloud/portfolio:client-latest
    env_file:
      - .env
    container_name: portfolio-client
    ports:
      - "127.0.0.1:8080:80"
    restart: unless-stopped
    working_dir: /usr/src/app
    profiles: ["portfolio"]
    environment:
      NODE_ENV: ${NODE_ENV}
      REACT_APP_API_URL: ${REACT_APP_API_URL}
    depends_on:
      - portfolio-server
    networks:
      - portfolio_network

networks:
  portfolio_network:
    driver: bridge

volumes:
  portfolio_db_data:
