version: "3.7"
services:
  client:
    container_name: client
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
  server:
    container_name: server
    build: ./server
    ports:
    - 5000:5000
    volumes:
      - ./server:/app
      - /app/node_modules
